org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m -Djava.net.preferIPv4Stack=true
android.useAndroidX=true
reactNativeArchitectures=armeabi-v7a,arm64-v8a,x86,x86_64
newArchEnabled=false
hermesEnabled=true
org.gradle.caching=false
org.gradle.vfs.watch=false
systemProp.sun.net.spi.nameservice.provider.1=dns,sun



//if file locking or other errpors occur, try this 
// ./gradlew clean --no-daemon  
