export const materialsData = {
  id: 'root',
  name: 'Engineering Materials',
  color: '#00D4FF',
  textColor: '#FFFFFF',
  description: 'Materials used in industrial and mechanical engineering applications',
  children: [
    {
      id: 'metals',
      name: 'Metals',
      color: '#FFB347',
      textColor: '#1A1A2E',
      icon:'⚙️',
      image:'https://pub-9a09ee6126034c0c9cbd772d75056b70.r2.dev/IndustrialMaterials/images/materials-images/metals/alloy-steel.jpg',
      description: 'Materials with metallic properties: conductivity, ductility, luster',
      properties: ['High thermal conductivity', 'Electrical conductivity', 'Ductility & malleability', 'Metallic luster'],
      applications: ['Structural components', 'Electrical wiring', 'Heat exchangers', 'Machinery parts'],
      children: [
        {
          id: 'ferrous',
          name: 'Ferrous',
          color: '#FF8C42',
          textColor: '#FFFFFF',
          description: 'Iron-based metals, typically magnetic',
          examples: ['Steels', 'Stainless steels', 'Tool and die steels', 'Cast irons'],
          properties: ['Magnetic properties', 'High strength', 'Prone to corrosion (except stainless)'],
          children: [
            {
              id: 'steels',
              name: 'Steels',
              color: '#E85D04',
              examples: ['Carbon Steel', 'Alloy Steel', 'Tool Steel'],
              uses: 'Construction, automotive, machinery',
            },
            {
              id: 'stainless',
              name: 'Stainless Steels',
              color: '#E85D04',
              examples: ['AISI 304', 'AISI 316', 'AISI 430'],
              uses: 'Kitchenware, chemical processing, medical',
            },
            {
              id: 'tool-steel',
              name: 'Tool & Die Steels',
              color: '#E85D04',
              examples: ['HSS', 'D2', 'O1'],
              uses: 'Cutting tools, dies, molds',
            },
            {
              id: 'cast-iron',
              name: 'Cast Irons',
              color: '#E85D04',
              examples: ['Gray CI', 'Ductile CI', 'White CI', 'Malleable CI'],
              uses: 'Engine blocks, pipes, machine beds',
            },
            {
                id: 'wrought-iron',
                name: 'Wrought Iron',
                color: '#E85D04',
                examples: ['Commercial wrought iron'],
                uses: 'Gates, chains, railings, decorative works',
            },

            {
                id: 'alloy-steel',
                name: 'Alloy Steel',
                color: '#E85D04',
                examples: ['Chromium Steel', 'Nickel Steel', 'Molybdenum Steel'],
                uses: 'Gears, shafts, pressure vessels, automotive parts',
            },

            {
                id: 'spring-steel',
                name: 'Spring Steel',
                color: '#E85D04',
                examples: ['High Carbon Spring Steel'],
                uses: 'Springs, suspension systems',
            },

            {
                id: 'bearing-steel',
                name: 'Bearing Steel',
                color: '#E85D04',
                examples: ['Chrome Steel SAE 52100'],
                uses: 'Ball bearings, roller bearings',
            },

            {
                id: 'heat-resistant-steel',
                name: 'Heat Resistant Steel',
                color: '#E85D04',
                examples: ['Inconel Steel'],
                uses: 'Boilers, turbines, furnaces',
            },
          ],
        },
        {
          id: 'nonferrous',
          name: 'Nonferrous',
          color: '#F4A261',
          textColor: '#1A1A2E',
          description: 'Metals without iron as base element',
          examples: ['Aluminum', 'Copper', 'Titanium', 'Tungsten', 'Others'],
          properties: ['Non-magnetic', 'Corrosion resistant', 'Lightweight (Al, Ti)'],
          children: [
            {
              id: 'aluminum',
              name: 'Aluminum',
              color: '#E76F51',
              examples: ['6061-T6', '7075', '2024'],
              uses: 'Aerospace, automotive, packaging',
            },
            {
              id: 'copper',
              name: 'Copper',
              color: '#E76F51',
              examples: ['Pure Cu', 'Brass', 'Bronze'],
              uses: 'Electrical wiring, heat exchangers, plumbing',
            },
            {
              id: 'titanium',
              name: 'Titanium',
              color: '#E76F51',
              examples: ['Ti-6Al-4V', 'Commercially Pure'],
              uses: 'Aerospace, biomedical implants, marine',
            },
            {
              id: 'tungsten',
              name: 'Tungsten',
              color: '#E76F51',
              examples: ['Pure W', 'WC-Co (Cemented Carbide)'],
              uses: 'Filaments, cutting tools, radiation shielding',
            },
            {
                id: 'magnesium',
                name: 'Magnesium',
                color: '#E76F51',
                examples: ['AZ31', 'ZK60'],
                uses: 'Aircraft, automotive lightweight parts',
            },

            {
                id: 'nickel',
                name: 'Nickel',
                color: '#E76F51',
                examples: ['Pure Nickel', 'Nickel Alloy'],
                uses: 'Heat exchangers, corrosion-resistant parts',
            },

            {
                id: 'zinc',
                name: 'Zinc',
                color: '#E76F51',
                examples: ['Galvanized Zinc'],
                uses: 'Galvanizing steel, die casting',
            },

            {
                id: 'lead',
                name: 'Lead',
                color: '#E76F51',
                examples: ['Pure Lead', 'Lead Alloy'],
                uses: 'Radiation shielding, batteries',
            },

            {
                id: 'tin',
                name: 'Tin',
                color: '#E76F51',
                examples: ['Pure Tin', 'Tin Coating'],
                uses: 'Food cans, soldering',
            },

            {
                id: 'brass',
                name: 'Brass',
                color: '#E76F51',
                examples: ['Cartridge Brass', 'Naval Brass'],
                uses: 'Valves, fittings, bearings',
            },

            {
                id: 'bronze',
                name: 'Bronze',
                color: '#E76F51',
                examples: ['Phosphor Bronze', 'Aluminum Bronze'],
                uses: 'Bearings, gears, marine components',
                },

                {
                id: 'superalloys',
                name: 'Super Alloys',
                color: '#E76F51',
                examples: ['Inconel', 'Monel', 'Hastelloy'],
                uses: 'Jet engines, gas turbines, high-temperature industries',
                },
          ],
        },
      ],
    },
    {
      id: 'plastics',
      name: 'Plastics',
      color: '#90EE90',
      textColor: '#1A1A2E',
      icon:'🧪',
      description: 'Synthetic or semi-synthetic organic polymers',
      properties: ['Lightweight', 'Corrosion resistant', 'Electrical insulation', 'Easy to mold'],
      applications: ['Packaging', 'Automotive parts', 'Electrical insulation', 'Consumer goods'],
      children: [
        {
          id: 'thermoplastics',
          name: 'Thermoplastics',
          color: '#7FDBDA',
          textColor: '#1A1A2E',
          description: 'Soften when heated, can be remelted and reshaped',
          examples: ['Acrylics', 'ABS', 'Nylons', 'Polyethylenes', 'PVC', 'Others'],
          properties: ['Recyclable', 'Reversible', 'Lower heat resistance'],
          children: [
            {
              id: 'acrylics',
              name: 'Acrylics (PMMA)',
              color: '#5EBDBD',
              examples: ['Plexiglas', 'Perspex'],
              uses: 'Transparent sheets, lenses, signage',
            },
            {
              id: 'abs',
              name: 'ABS',
              color: '#5EBDBD',
              examples: ['Standard ABS', 'High-impact ABS'],
              uses: 'LEGO bricks, automotive trim, 3D printing',
            },
            {
              id: 'nylons',
              name: 'Nylons (PA)',
              color: '#5EBDBD',
              examples: ['PA6', 'PA66', 'PA12'],
              uses: 'Gears, bearings, fasteners, textiles',
            },
            {
              id: 'polyethylene',
              name: 'Polyethylenes',
              color: '#5EBDBD',
              examples: ['HDPE', 'LDPE', 'UHMWPE'],
              uses: 'Bottles, pipes, films, containers',
            },
            {
              id: 'pvc',
              name: 'PVC',
              color: '#5EBDBD',
              examples: ['Rigid PVC', 'Flexible PVC'],
              uses: 'Pipes, flooring, cable insulation',
            },
            {
            id: 'ptfe',
            name: 'PTFE (Teflon)',
            color: '#5EBDBD',
            examples: ['Virgin PTFE', 'Filled PTFE'],
            uses: 'Seals, bearings, chemical pipes',
            },

            {
            id: 'polycarbonate',
            name: 'Polycarbonate',
            color: '#5EBDBD',
            examples: ['Transparent PC'],
            uses: 'Safety shields, helmets',
            },

            {
            id: 'polypropylene',
            name: 'Polypropylene',
            color: '#5EBDBD',
            examples: ['PP Homopolymer'],
            uses: 'Containers, automotive interiors',
            },

            {
            id: 'delrin',
            name: 'Delrin (POM)',
            color: '#5EBDBD',
            examples: ['Acetal Resin'],
            uses: 'Precision gears, bushes',
            },
          ],
        },
        {
          id: 'thermosets',
          name: 'Thermosets',
          color: '#6BCB77',
          textColor: '#1A1A2E',
          description: 'Permanently set after curing, cannot be remelted',
          examples: ['Epoxies', 'Phenolics', 'Polyimides', 'Others'],
          properties: ['High heat resistance', 'Rigid', 'Irreversible curing'],
          children: [
            {
              id: 'epoxies',
              name: 'Epoxies',
              color: '#4AA96C',
              examples: ['Standard Epoxy', 'Structural Epoxy'],
              uses: 'Adhesives, coatings, composites matrix',
            },
            {
              id: 'phenolics',
              name: 'Phenolics',
              color: '#4AA96C',
              examples: ['Bakelite', 'Novolac'],
              uses: 'Electrical insulators, handles, brake pads',
            },
            {
              id: 'polyimides',
              name: 'Polyimides',
              color: '#4AA96C',
              examples: ['Kapton', 'Vespel'],
              uses: 'High-temp insulation, aerospace, semiconductors',
            },
          ],
        },
        {
          id: 'elastomers',
          name: 'Elastomers',
          color: '#4D96FF',
          textColor: '#FFFFFF',
          description: 'Rubber-like materials with high elasticity',
          examples: ['Rubbers', 'Silicones', 'Polyurethanes'],
          properties: ['High elasticity', 'Can recover shape', 'Vibration damping'],
          children: [
            {
              id: 'rubbers',
              name: 'Rubbers',
              color: '#3A7BD5',
              examples: ['Natural Rubber', 'SBR', 'NBR', 'EPDM'],
              uses: 'Tires, seals, gaskets, hoses',
            },
            {
              id: 'silicones',
              name: 'Silicones',
              color: '#3A7BD5',
              examples: ['RTV Silicone', 'Liquid Silicone Rubber'],
              uses: 'Seals, medical devices, cookware',
            },
            {
              id: 'polyurethanes',
              name: 'Polyurethanes',
              color: '#3A7BD5',
              examples: ['Flexible PU', 'Rigid PU Foam'],
              uses: 'Foam cushions, coatings, wheels, insulation',
            },
            {
                id: 'neoprene',
                name: 'Neoprene',
                color: '#3A7BD5',
                examples: ['Industrial Neoprene'],
                uses: 'Belts, gaskets, hoses',
                },

                {
                id: 'viton',
                name: 'Viton',
                color: '#3A7BD5',
                examples: ['FKM Rubber'],
                uses: 'Oil seals, fuel-resistant gaskets',
                },

                {
                id: 'butyl-rubber',
                name: 'Butyl Rubber',
                color: '#3A7BD5',
                examples: ['Industrial Butyl'],
                uses: 'Tires, vacuum seals',
                },
          ],
        },
      ],
    },
    {
      id: 'ceramics',
      name: 'Ceramics & Others',
      color: '#000',
      textColor: '#1A1A2E',
      icon:'🧱',
      description: 'Inorganic, non-metallic materials with high-temperature stability',
      properties: ['High hardness', 'Brittle', 'High temp resistance', 'Electrical insulation', 'Chemical inertness'],
      applications: ['Cutting tools', 'Insulators', 'Refractories', 'Biomedical implants', 'Aerospace tiles'],
      children: [
        {
          id: 'oxides',
          name: 'Oxides',
          color: '#E0E0E0',
          examples: ['Alumina (Al₂O₃)', 'Zirconia (ZrO₂)', 'Silica (SiO₂)'],
          uses: 'Insulators, refractories, abrasives',
        },
        {
          id: 'nitrides',
          name: 'Nitrides',
          color: '#E0E0E0',
          examples: ['Silicon Nitride (Si₃N₄)', 'Boron Nitride (BN)'],
          uses: 'Bearings, cutting tools, high-temp parts',
        },
        {
          id: 'carbides',
          name: 'Carbides',
          color: '#E0E0E0',
          examples: ['Silicon Carbide (SiC)', 'Tungsten Carbide (WC)', 'Boron Carbide (B₄C)'],
          uses: 'Abrasive, armor, cutting tools, wear parts',
        },
        {
          id: 'glasses',
          name: 'Glasses',
          color: '#E0E0E0',
          examples: ['Soda-lime', 'Borosilicate', 'Fused Silica'],
          uses: 'Windows, lenses, containers, fiber optics',
        },
        {
          id: 'glass-ceramics',
          name: 'Glass Ceramics',
          color: '#E0E0E0',
          examples: ['Pyroceram', 'Zerodur'],
          uses: 'Cookware, telescope mirrors, dental',
        },
        {
          id: 'graphite',
          name: 'Graphite',
          color: '#E0E0E0',
          examples: ['Natural Graphite', 'Synthetic Graphite'],
          uses: 'Electrodes, lubricants, nuclear moderators',
        },
        {
          id: 'diamond',
          name: 'Diamond',
          color: '#E0E0E0',
          examples: ['Natural Diamond', 'Synthetic CVD Diamond'],
          uses: 'Cutting tools, heat spreaders, jewelry',
        },
        {
            id: 'refractories',
            name: 'Refractories',
            color: '#E0E0E0',
            examples: ['Fire Brick', 'Silica Brick'],
            uses: 'Furnaces, kilns, steel plants',
            },

            {
            id: 'piezoelectric',
            name: 'Piezoelectric Ceramics',
            color: '#E0E0E0',
            examples: ['PZT'],
            uses: 'Sensors, ultrasonic machines',
            },
      ],
    },
    {
      id: 'composites',
      name: 'Composites',
      color: '#FF6B6B',
      textColor: '#FFFFFF',
      icon:'🧩',
      description: 'Materials made from two or more constituent materials with different properties',
      properties: ['High strength-to-weight ratio', 'Tailorable properties', 'Anisotropic', 'Corrosion resistant'],
      applications: ['Aerospace structures', 'Automotive body panels', 'Wind turbine blades', 'Sports equipment', 'Marine vessels'],
      children: [
        {
          id: 'reinforced-plastics',
          name: 'Reinforced Plastics',
          color: '#EE5A5A',
          examples: ['GFRP (Glass Fiber)', 'CFRP (Carbon Fiber)', 'Kevlar/Aramid'],
          uses: 'Boats, car panels, pipes, tanks',
        },
        {
          id: 'metal-matrix',
          name: 'Metal-Matrix',
          color: '#EE5A5A',
          examples: ['Al-SiC', 'Ti-Boron', 'Mg-Carbon'],
          uses: 'Automotive pistons, aerospace, electronics',
        },
        {
          id: 'ceramic-matrix',
          name: 'Ceramic-Matrix',
          color: '#EE5A5A',
          examples: ['C/SiC', 'SiC/SiC', 'Ox/Ox'],
          uses: 'Jet engine components, brake discs, heat shields',
        },
        {
          id: 'laminates',
          name: 'Laminates',
          color: '#EE5A5A',
          examples: ['Plywood', 'Glulam', 'CLT'],
          uses: 'Construction, furniture, packaging',
        },
        {
          id: 'others-composite',
          name: 'Others',
          color: '#EE5A5A',
          examples: ['Sandwich panels', 'Nanocomposites', 'Hybrid composites'],
          uses: 'Aerospace, automotive, infrastructure',
        },
      ],
    },

{
  id: 'smart-materials',
  name: 'Smart Materials',
  color: '#9B5DE5',
  textColor: '#FFFFFF',
  icon:'🧩',
  description: 'Materials that react to environmental changes',
  properties: [
    'Adaptive',
    'Responsive',
    'High-performance'
  ],
  applications: [
    'Robotics',
    'Aerospace',
    'Medical engineering'
  ],
  children: [
    {
      id: 'shape-memory-alloy',
      name: 'Shape Memory Alloy',
      color: '#8A4FFF',
      examples: ['Nitinol'],
      uses: 'Actuators, medical stents',
    },
    {
      id: 'piezo-materials',
      name: 'Piezoelectric Materials',
      color: '#8A4FFF',
      examples: ['PZT'],
      uses: 'Sensors, vibration control',
    },
    {
      id: 'self-healing',
      name: 'Self Healing Materials',
      color: '#8A4FFF',
      examples: ['Polymer self-healing composites'],
      uses: 'Aircraft, advanced manufacturing',
    },
  ],
}

  ],
};

