export const CATEGORIES = [
  { id: 'all', label: 'All' },
  { id: 'dimensional', label: 'Dimensional' },
  { id: 'angular', label: 'Angular' },
  { id: 'surface', label: 'Surface' },
  { id: 'comparator', label: 'Comparators' },
  { id: 'force', label: 'Force & Torque' },
  { id: 'hardness', label: 'Hardness' },
  { id: 'thread', label: 'Thread' },
  { id: 'bore', label: 'Bore & Hole' },
];

export const INSTRUMENTS = [
  {
    id: '1',
    name: 'Vernier Caliper',
    category: 'dimensional',
    categoryLabel: 'Dimensional / Linear',
    accuracy: '±0.01 mm',
    standard: 'ISO 3599',
    color: '#1F4E79',
    lightColor: '#D6E4F0',
    image: require('../../assets/images/measuring/vernier.png'),
    description:
      'A Vernier caliper measures internal/external dimensions, depths, and step heights using a main scale and sliding vernier scale. Available in analog, dial, and digital versions.',
    useCases: [
      'Measuring outer diameter of shafts, rods, and cylinders',
      'Measuring inner diameter of holes, bores, and slots',
      'Measuring depth of holes, slots, and recesses',
      'Measuring step heights and shoulder distances',
      'Quick shop-floor quality checks',
      'Post-machining inspection of parts',
    ],
    specs: [
      { param: 'Measuring Range', value: '0–150 / 300 / 600 / 1000 mm' },
      { param: 'Accuracy (Analog)', value: '±0.02 mm' },
      { param: 'Accuracy (Digital)', value: '±0.01 mm' },
      { param: 'Resolution (Digital)', value: '0.01 mm' },
      { param: 'Material', value: 'Hardened stainless steel' },
      { param: 'Jaw Types', value: 'External, internal jaws, depth rod' },
      { param: 'Standards', value: 'DIN 862 / ISO 3599 / JIS B 7507' },
      { param: 'IP Rating (Digital)', value: 'IP 54' },
      { param: 'Calibration', value: 'Gauge blocks or ring gauges' },
    ],
    applications: [
      'Automotive: engine parts, brake components',
      'Aerospace: turbine blades, fasteners',
      'Tool & die making',
      'Mold and injection molding inspection',
      'General workshop measurement',
    ],
  },
  {
    id: '2',
    name: 'Micrometer (Screw Gauge)',
    category: 'dimensional',
    categoryLabel: 'Dimensional / Linear',
    accuracy: '±0.002 mm',
    standard: 'ISO 3611',
    color: '#155724',
    lightColor: '#D4EDDA',
    image: require('../../assets/images/measuring/vernier.png'),
    description:
      'A micrometer uses a precision-ground screw to measure small distances or thicknesses with extremely high accuracy, typically to 0.001 mm. Types include outside, inside, and depth micrometers.',
    useCases: [
      'Measuring wire diameter, sheet thickness',
      'Checking diameter of precision ground shafts',
      'Measuring wall thickness of tubes and cylinders',
      'Thread pitch diameter measurement',
      'Bore diameter checking with inside micrometers',
      'Quality inspection of precision machined components',
    ],
    specs: [
      { param: 'Measuring Range', value: '0–25 mm (up to 1000 mm)' },
      { param: 'Resolution', value: '0.001 mm / 0.0001 mm (digital)' },
      { param: 'Accuracy', value: '±0.002 mm to ±0.004 mm' },
      { param: 'Thimble Graduations', value: '0.5 mm per revolution' },
      { param: 'Anvil Material', value: 'Tungsten carbide tipped' },
      { param: 'Spindle Thread', value: '0.5 mm pitch precision ground' },
      { param: 'Thermal Expansion', value: 'Heat-insulating plastic grip' },
      { param: 'Standards', value: 'ISO 3611 / DIN 863 / JIS B 7502' },
      { param: 'Calibration', value: 'Gauge blocks / precision standards' },
    ],
    applications: [
      'Precision machining: CNC turning, grinding, milling',
      'Bearing and shaft tolerance verification',
      'Gear manufacturing',
      'Aerospace component inspection',
      'Metrology laboratory measurements',
    ],
  },
  {
    id: '3',
    name: 'Height Gauge',
    category: 'dimensional',
    categoryLabel: 'Dimensional / Linear',
    accuracy: '±0.02 mm',
    standard: 'ISO 13225',
    color: '#7B3F00',
    lightColor: '#FDEBD0',
    image: require('../../assets/images/measuring/vernier.png'),
    description:
      'A height gauge measures the height of objects or marks lines at specific heights from a reference surface plate. Used with a granite or steel surface plate.',
    useCases: [
      'Measuring component height from a datum surface',
      'Scribing parallel lines at specific heights for layout',
      'Checking flatness and squareness of components',
      'Measuring step heights and shoulder positions',
      'Setting up workpieces on machining centers',
    ],
    specs: [
      { param: 'Measuring Range', value: '300 / 600 / 1000 mm' },
      { param: 'Resolution', value: '0.01 mm (digital)' },
      { param: 'Accuracy', value: '±0.02 mm to ±0.05 mm' },
      { param: 'Column Type', value: 'Round or square hardened column' },
      { param: 'Base Material', value: 'Cast iron or granite' },
      { param: 'Display', value: 'LCD / analog dial' },
      { param: 'Standards', value: 'ISO 13225 / DIN 2276' },
      { param: 'Calibration', value: 'Gauge blocks on certified surface plate' },
    ],
    applications: [
      'Tool room inspection and layout work',
      'Jig and fixture manufacturing',
      'Mold and die inspection',
      'Quality control departments',
    ],
  },
  {
    id: '4',
    name: 'Feeler Gauge',
    category: 'dimensional',
    categoryLabel: 'Clearance / Gap Measurement',
    accuracy: '±0.005 mm',
    standard: 'DIN 2275',
    color: '#4A235A',
    lightColor: '#E8DAEF',
    image: require('../../assets/images/measuring/vernier.png'),
    description:
      'A feeler gauge consists of a set of thin metal blades of precisely known thickness, used to measure gaps and clearances between two surfaces.',
    useCases: [
      'Checking valve clearances in engines',
      'Setting spark plug gaps',
      'Measuring bearing clearances',
      'Checking gear backlash',
      'Setting brake caliper clearances',
      'Measuring weld gaps before welding',
    ],
    specs: [
      { param: 'Blade Thickness Range', value: '0.03 mm to 1.00 mm' },
      { param: 'Number of Blades', value: '13 to 26 blades per set' },
      { param: 'Material', value: 'Hardened carbon or stainless steel' },
      { param: 'Blade Length', value: '75 mm to 100 mm' },
      { param: 'Accuracy', value: '±0.005 mm' },
      { param: 'Finish', value: 'Polished or matte' },
      { param: 'Standards', value: 'DIN 2275 / JIS B 7524' },
    ],
    applications: [
      'Automobile engine maintenance and repair',
      'Diesel engine servicing',
      'Compressor and pump maintenance',
      'Heavy equipment servicing',
    ],
  },
  {
    id: '5',
    name: 'Steel Rule / Steel Tape',
    category: 'dimensional',
    categoryLabel: 'Dimensional / Linear',
    accuracy: '±0.5 mm',
    standard: 'ISO 2768',
    color: '#1A5276',
    lightColor: '#D6EAF8',
    image: require('../../assets/images/measuring/vernier.png'),
    description:
      'The most basic linear measurement tool made from stainless or carbon steel. Rules are rigid for short measurements; tapes are flexible for longer distances.',
    useCases: [
      'Basic length measurements on the shop floor',
      'Rough checking of raw material dimensions',
      'Layout work and marking',
      'Measuring distances on large workpieces',
    ],
    specs: [
      { param: 'Length Range', value: '150 mm to 50 m (tape)' },
      { param: 'Graduation', value: '0.5 mm finest' },
      { param: 'Accuracy', value: 'Class I: ±0.1 mm, Class II: ±0.2 mm' },
      { param: 'Material', value: 'Stainless steel / carbon steel' },
      { param: 'Standards', value: 'ISO 2768 / DIN 866' },
    ],
    applications: [
      'General workshop and fabrication',
      'Construction and structural steel',
      'Sheet metal layout',
      'Raw material inspection',
    ],
  },
  {
    id: '6',
    name: 'Bevel Protractor',
    category: 'angular',
    categoryLabel: 'Angular Measurement',
    accuracy: "5'",
    standard: 'DIN 2264',
    color: '#1F618D',
    lightColor: '#D6EAF8',
    image: require('../../assets/images/measuring/vernier.png'),
    description:
      "A bevel protractor is a precision angular measuring tool with a movable blade and vernier scale to measure angles with accuracy to 5 minutes (5') of arc.",
    useCases: [
      'Measuring angles of machined components',
      'Setting cutting tools at specific angles',
      'Checking taper angles on turned parts',
      'Verifying angular features in castings',
      'Layout work on precision components',
    ],
    specs: [
      { param: 'Measuring Range', value: '0°–360°' },
      { param: 'Vernier Accuracy', value: "5 minutes (5') of arc" },
      { param: 'Main Scale Division', value: '1° (degrees)' },
      { param: 'Blade Length', value: '150 mm or 300 mm' },
      { param: 'Material', value: 'Hardened stainless steel' },
      { param: 'Standards', value: 'DIN 2264 / JIS B 7525' },
      { param: 'Calibration', value: 'Master angles / precision angle plates' },
    ],
    applications: [
      'Tool & die making',
      'Sheet metal fabrication',
      'Precision machining operations',
      'Inspection of angular surfaces and tapers',
    ],
  },
  {
    id: '7',
    name: 'Sine Bar',
    category: 'angular',
    categoryLabel: 'Angular Measurement (High Precision)',
    accuracy: '±5"',
    standard: 'BS 3217',
    color: '#0E4D3B',
    lightColor: '#D5F5E3',
    image: require('../../assets/images/measuring/vernier.png'),
    description:
      'A sine bar measures or sets angles using slip (gauge) blocks, working on the trigonometric principle of a right-angled triangle. Accurate to seconds of arc.',
    useCases: [
      'Setting precise angles on surface grinders and milling machines',
      'Inspecting angles on precision components',
      'Calibrating angular fixtures and jigs',
      'Measuring Morse taper and precision tapers',
      'Verifying angles in optical and aerospace components',
    ],
    specs: [
      { param: 'Centre Distance (L)', value: '100 mm, 200 mm, 300 mm' },
      { param: 'Angular Range', value: '0° to 45° (best), up to 60°' },
      { param: 'Accuracy', value: '±3 to ±5 seconds of arc' },
      { param: 'Body Material', value: 'Hardened alloy steel' },
      { param: 'Roll Type', value: 'Precision ground rollers' },
      { param: 'Top Surface Flatness', value: '0.003 mm per 100 mm' },
      { param: 'Standards', value: 'IS 5359 / DIN 874 / BS 3217' },
      { param: 'Used With', value: 'Slip gauges, surface plate, dial indicator' },
    ],
    applications: [
      'Precision tool room operations',
      'Gauge and fixture manufacturing',
      'Aerospace component inspection',
      'Optical instrument manufacturing',
    ],
  },
  {
    id: '8',
    name: 'CMM',
    category: 'surface',
    categoryLabel: '3D Dimensional Measurement',
    accuracy: '1.5–3 µm',
    standard: 'ISO 10360',
    color: '#512E5F',
    lightColor: '#E8DAEF',
    image: require('../../assets/images/measuring/vernier.png'),
    description:
      'A Coordinate Measuring Machine (CMM) measures the geometry of physical objects by sensing discrete points on the surface with a probe in three dimensions (X, Y, Z).',
    useCases: [
      'Full 3D inspection of complex machined components',
      'Reverse engineering of existing parts',
      'Verifying GD&T (Geometric Dimensioning & Tolerancing)',
      'First Article Inspection (FAI) in aerospace/automotive',
      'Mold cavity inspection and surface mapping',
      'Statistical process control data collection',
    ],
    specs: [
      { param: 'Measuring Volume', value: '300×300×250 mm up to 4000×2000×2000 mm' },
      { param: 'Volumetric Accuracy', value: '1.5–3 µm' },
      { param: 'Probe Types', value: 'Touch trigger, scanning, optical, laser' },
      { param: 'Drive System', value: 'Manual, motorized (DCC)' },
      { param: 'Probe Force', value: '0.02 N to 0.5 N' },
      { param: 'Operating Temp.', value: '20°C ±2°C (controlled environment)' },
      { param: 'Software', value: 'PC-DMIS, CALYPSO, Polyworks, Modus' },
      { param: 'Standards', value: 'ISO 10360 / VDI/VDE 2617' },
      { param: 'Calibration', value: 'Certified reference sphere and artifacts' },
    ],
    applications: [
      'Automotive engine and transmission inspection',
      'Aerospace structural component verification',
      'Medical device manufacturing',
      'Defense and precision instrument manufacturing',
    ],
  },
  {
    id: '9',
    name: 'Surface Roughness Tester',
    category: 'surface',
    categoryLabel: 'Surface Finish Measurement',
    accuracy: '0.01 µm',
    standard: 'ISO 4287',
    color: '#7D3C98',
    lightColor: '#F4ECF7',
    image: require('../../assets/images/measuring/vernier.png'),
    description:
      'A surface roughness tester (profilometer) uses a diamond-tipped stylus to trace surface texture. Key parameters: Ra (average roughness), Rz (mean roughness depth), Rmax.',
    useCases: [
      'Verifying surface finish after grinding or turning',
      'Checking sealing surfaces (gasket faces, O-ring grooves)',
      'Bearing journal surface quality verification',
      'Hydraulic cylinder bore quality control',
      'Compliance with surface finish drawings',
      'Investigating friction and wear-related failures',
    ],
    specs: [
      { param: 'Measuring Parameters', value: 'Ra, Rz, Rmax, Rq, Rt, Rsk, etc.' },
      { param: 'Ra Range', value: '0.05 µm to 160 µm' },
      { param: 'Stylus Tip Radius', value: '2 µm or 5 µm (diamond tip)' },
      { param: 'Stylus Force', value: '0.7 mN to 4 mN' },
      { param: 'Traverse Length', value: '1.75 mm to 50 mm' },
      { param: 'Cut-off Values (λc)', value: '0.08, 0.25, 0.8, 2.5, 8 mm' },
      { param: 'Display', value: 'LCD / color with graphical profile' },
      { param: 'Standards', value: 'ISO 4287 / ISO 4288 / ASME B46.1' },
      { param: 'Calibration', value: 'Certified roughness comparison specimens' },
    ],
    applications: [
      'Precision grinding and lapping operations',
      'Hydraulic and pneumatic component manufacturing',
      'Automotive engine parts (cylinder walls, crankshafts)',
      'Aerospace component surface validation',
    ],
  },
  {
    id: '10',
    name: 'Dial Indicator (Dial Gauge)',
    category: 'comparator',
    categoryLabel: 'Comparator / Deviation Measurement',
    accuracy: '±0.001 mm',
    standard: 'ISO 463',
    color: '#1F618D',
    lightColor: '#D6EAF8',
    image: require('../../assets/images/measuring/vernier.png'),
    description:
      'A dial indicator converts small linear plunger movement into rotary motion of a pointer on a dial. Widely used for detecting runout, alignment errors, and surface variations.',
    useCases: [
      'Checking roundness and runout of rotating parts',
      'Aligning workpieces on machine tables',
      'Detecting surface flatness variations',
      'Checking parallelism and squareness',
      'Verifying end play and axial bearing movement',
      'Used in jig boring and surface grinder setups',
    ],
    specs: [
      { param: 'Travel Range', value: '1, 5, 10, 25, 50 mm' },
      { param: 'Graduation', value: '0.001 mm / 0.0001 mm (test indicator)' },
      { param: 'Accuracy', value: '±0.005 mm to ±0.01 mm' },
      { param: 'Dial Face Diameter', value: '36 mm, 58 mm, 80 mm' },
      { param: 'Stem Diameter', value: '8 mm (standard mounting)' },
      { param: 'Contact Point', value: 'Carbide or ruby ball tip' },
      { param: 'Repeatability', value: '±0.001 mm' },
      { param: 'Standards', value: 'ISO 463 / DIN 878 / JIS B 7503' },
      { param: 'Calibration', value: 'Gauge blocks on surface plate' },
    ],
    applications: [
      'CNC machining setup and verification',
      'Lathe and milling machine work holding setup',
      'CMM probe calibration reference',
      'Automotive wheel alignment equipment',
      'Assembly inspection of precision components',
    ],
  },
  {
    id: '11',
    name: 'Optical Comparator',
    category: 'comparator',
    categoryLabel: 'Optical / Profile Measurement',
    accuracy: '±0.003 mm',
    standard: 'JIS B 7184',
    color: '#145A32',
    lightColor: '#D5F5E3',
    image: require('../../assets/images/measuring/vernier.png'),
    description:
      'An optical comparator (profile projector) projects a magnified shadow silhouette of a part onto a screen for comparison with an overlay template. Non-contact method.',
    useCases: [
      'Inspecting thread form and pitch',
      'Checking gear tooth profiles',
      'Measuring small stamped and formed parts',
      'Verifying complex contour shapes',
      'Inspecting drill and cutting tool geometry',
      'Checking small radii, chamfers, and undercuts',
    ],
    specs: [
      { param: 'Screen Diameter', value: '300 mm, 400 mm, 500 mm' },
      { param: 'Magnification', value: '5×, 10×, 20×, 25×, 50×, 100×' },
      { param: 'Stage Travel (X×Y)', value: 'Up to 300 mm × 150 mm' },
      { param: 'Resolution', value: '0.001 mm (with digital readout)' },
      { param: 'Light Source', value: 'LED or halogen, transmitted/surface' },
      { param: 'Accuracy', value: '±0.003 mm' },
      { param: 'Overlay Charts', value: 'Thread, radius, angle (DIN, ISO, ANSI)' },
      { param: 'Standards', value: 'JIS B 7184 / ISO 10110' },
    ],
    applications: [
      'Small parts manufacturing (watch parts, electronics)',
      'Fastener and threaded component inspection',
      'Cutting tool geometry verification',
      'Stamping and sheet metal part inspection',
    ],
  },
  {
    id: '12',
    name: 'Torque Wrench',
    category: 'force',
    categoryLabel: 'Torque Measurement',
    accuracy: '±4% reading',
    standard: 'ISO 6789',
    color: '#784212',
    lightColor: '#FDEBD0',
    image: require('../../assets/images/measuring/vernier.png'),
    description:
      'A torque wrench applies a specific torque to fasteners such as nuts and bolts, ensuring joints are tightened to required specification to prevent loosening or damage.',
    useCases: [
      'Tightening cylinder head bolts to spec',
      'Assembly of flanged joints in pressure vessels',
      'Automotive wheel nut torquing',
      'Structural bolting in construction and bridges',
      'Assembly of aircraft fasteners',
      'Industrial machinery maintenance and overhaul',
    ],
    specs: [
      { param: 'Torque Range', value: '1–25 Nm / 40–200 Nm / up to 3000 Nm' },
      { param: 'Accuracy', value: '±3–5% of reading (Class I: ±4%)' },
      { param: 'Drive Size', value: '1/4", 3/8", 1/2", 3/4", 1" square drive' },
      { param: 'Type', value: 'Click, beam, electronic, dial indicating' },
      { param: 'Graduation', value: '1 Nm increments (typical)' },
      { param: 'Standards', value: 'ISO 6789 / DIN 3122 / ASME B107.300' },
      { param: 'Calibration Interval', value: 'Every 5,000 cycles or annually' },
      { param: 'Calibration Method', value: 'Torque analyzer or test bench' },
    ],
    applications: [
      'Automotive assembly and engine rebuilding',
      'Aerospace maintenance and repair',
      'Power plant and turbine maintenance',
      'Structural steel erection',
    ],
  },
  {
    id: '13',
    name: 'Bore Gauge',
    category: 'bore',
    categoryLabel: 'Bore & Hole Measurement',
    accuracy: '±0.005 mm',
    standard: 'ISO 463',
    color: '#1A5276',
    lightColor: '#D6EAF8',
    image: require('../../assets/images/measuring/vernier.png'),
    description:
      'A bore gauge measures internal diameters by expanding spring-loaded contacts to the bore walls, then transferring the measurement to a micrometer or dial indicator.',
    useCases: [
      'Measuring internal bore diameters in cylinders',
      'Checking bearing housing bores',
      'Measuring deep blind holes',
      'Verifying bore roundness and taper',
      'Checking gear hub bore dimensions',
    ],
    specs: [
      { param: 'Measuring Range', value: '8–300 mm (typical set)' },
      { param: 'Accuracy', value: '±0.005 mm' },
      { param: 'Type', value: 'Telescoping, dial bore gauge, 3-point bore gauge' },
      { param: 'Resolution (3-point)', value: '0.001 mm' },
      { param: 'Material', value: 'Hardened steel contact points' },
      { param: 'Standards', value: 'ISO 463' },
      { param: 'Used With', value: 'Outside micrometer or dial indicator' },
    ],
    applications: [
      'Engine cylinder reboring and honing inspection',
      'Hydraulic cylinder bore measurement',
      'Pump and compressor maintenance',
      'CNC machining bore verification',
    ],
  },
  {
    id: '14',
    name: 'Plug & Ring Gauge',
    category: 'bore',
    categoryLabel: 'Bore & Hole Measurement',
    accuracy: 'IT Grade 4–6',
    standard: 'ISO 286',
    color: '#0E4D3B',
    lightColor: '#D5F5E3',
    image: require('../../assets/images/measuring/vernier.png'),
    description:
      'Plug gauges (for holes) and ring gauges (for shafts) are GO/NO-GO type gauges for rapid pass/fail dimensional checking. No numerical readout — accept or reject only.',
    useCases: [
      'GO/NO-GO inspection of hole diameters',
      'Checking shaft diameter against tolerance',
      'High-volume production line sorting',
      'Final inspection before assembly',
      'Thread pitch diameter verification',
    ],
    specs: [
      { param: 'Gauge Types', value: 'GO, NO-GO, combined' },
      { param: 'Tolerance Grade', value: 'IT Grade 4–6 (gauge tolerance)' },
      { param: 'Material', value: 'Tool steel or tungsten carbide' },
      { param: 'Hardness', value: '58–65 HRC' },
      { param: 'Surface Finish', value: 'Ra 0.1 µm or better' },
      { param: 'Standards', value: 'ISO 286 / DIN 7162 / ASME B47.1' },
      { param: 'Calibration', value: 'CMM or bench micrometer' },
    ],
    applications: [
      'Mass production quality control',
      'Automotive assembly line inspection',
      'Fastener and nut/bolt manufacturing',
      'Hydraulic components go/no-go sorting',
    ],
  },
  {
    id: '15',
    name: 'Thread Pitch Gauge',
    category: 'thread',
    categoryLabel: 'Thread Measurement',
    accuracy: '±0.01 mm pitch',
    standard: 'DIN 2256',
    color: '#4A235A',
    lightColor: '#E8DAEF',
    image: require('../../assets/images/measuring/vernier.png'),
    description:
      'A thread pitch gauge is a set of thin blades with tooth profiles matching standard thread pitches, used to quickly identify the pitch of a thread by finding the best-matching blade.',
    useCases: [
      'Identifying thread pitch of unknown fasteners',
      'Verifying metric vs. imperial threads',
      'Selecting correct replacement fasteners',
      'Checking thread pitch in maintenance and repair',
    ],
    specs: [
      { param: 'Pitch Range (Metric)', value: '0.25 mm to 6 mm' },
      { param: 'Pitch Range (Imperial)', value: '4 to 80 TPI' },
      { param: 'Number of Blades', value: '20 to 30 per set (typical)' },
      { param: 'Material', value: 'Hardened stainless steel' },
      { param: 'Thread Forms', value: 'Metric, UNC, UNF, BSW, BSF' },
      { param: 'Standards', value: 'DIN 2256 / JIS B 0252' },
    ],
    applications: [
      'Maintenance and repair workshops',
      'Fastener stockrooms',
      'Field service engineering',
      'Manufacturing incoming inspection',
    ],
  },
  {
    id: '16',
    name: 'Thread Micrometer',
    category: 'thread',
    categoryLabel: 'Thread Measurement',
    accuracy: '±0.004 mm',
    standard: 'ISO 3611',
    color: '#784212',
    lightColor: '#FDEBD0',
    image: require('../../assets/images/measuring/vernier.png'),
    description:
      'A thread micrometer measures the pitch diameter of external threads using special interchangeable anvil and spindle tips shaped to contact the thread flanks accurately.',
    useCases: [
      'Measuring pitch diameter of screw threads',
      'Verifying thread tolerance class (6g, 6H, etc.)',
      'Incoming inspection of threaded fasteners',
      'Thread gauge calibration reference',
      'Precision lead screw thread checking',
    ],
    specs: [
      { param: 'Measuring Range', value: '0–25 mm (each range)' },
      { param: 'Resolution', value: '0.001 mm' },
      { param: 'Accuracy', value: '±0.004 mm' },
      { param: 'Anvil Type', value: 'V-shaped thread anvil' },
      { param: 'Spindle Type', value: 'Conical thread spindle tip' },
      { param: 'Interchangeable Tips', value: 'Various thread forms and pitches' },
      { param: 'Standards', value: 'ISO 3611 / DIN 863' },
    ],
    applications: [
      'Precision fastener manufacturing',
      'Lead screw and worm gear production',
      'Thread gauge calibration laboratories',
      'Aerospace threaded component inspection',
    ],
  },
  {
    id: '17',
    name: 'Rockwell Hardness Tester',
    category: 'hardness',
    categoryLabel: 'Hardness Testing',
    accuracy: '±0.5 HRC',
    standard: 'ISO 6508',
    color: '#17202A',
    lightColor: '#D5D8DC',
    image: require('../../assets/images/measuring/vernier.png'),
    description:
      'The Rockwell hardness test measures hardness by pressing a diamond cone (Brale) or ball indenter into the surface under a set load. Derived from depth of penetration.',
    useCases: [
      'Testing hardness of heat-treated steel components',
      'Checking case depth hardness of carburized parts',
      'Incoming material inspection and certification',
      'Quality control of tool steels and high-speed steels',
      'Verifying temper (hardness) of springs',
      'Final inspection of hardened gears and shafts',
    ],
    specs: [
      { param: 'Hardness Scales', value: 'HRA, HRB, HRC (15 scales total)' },
      { param: 'HRC Range', value: '20–68 HRC (most common)' },
      { param: 'Minor Load', value: '10 kgf (98 N)' },
      { param: 'Major Load', value: '60 kgf, 100 kgf, or 150 kgf' },
      { param: 'Indenter (HRC)', value: '120° diamond cone (Brale)' },
      { param: 'Indenter (HRB)', value: '1/16 inch (1.588 mm) steel ball' },
      { param: 'Test Cycle Time', value: '5–10 seconds per test' },
      { param: 'Standards', value: 'ISO 6508 / ASTM E18 / DIN 50103' },
      { param: 'Calibration', value: 'Certified hardness reference blocks' },
    ],
    applications: [
      'Heat treatment shops and quench-temper facilities',
      'Steel service centers',
      'Automotive and gear manufacturing QC',
      'Tool and die manufacturing inspection',
      'Aerospace materials testing laboratory',
    ],
  },
  {
    id: '18',
    name: 'Brinell Hardness Tester',
    category: 'hardness',
    categoryLabel: 'Hardness Testing',
    accuracy: '±5 HB',
    standard: 'ASTM E10',
    color: '#2E4057',
    lightColor: '#D6E4F0',
    image: require('../../assets/images/measuring/vernier.png'),
    description:
      'The Brinell test uses a 10 mm tungsten carbide ball pressed into the material under heavy load. Hardness number (HB) is calculated from the diameter of the indentation.',
    useCases: [
      'Testing castings, forgings, and soft metals',
      'Measuring hardness of rough or coarse-grained surfaces',
      'Incoming inspection of structural steel',
      'Checking hardness of weld heat-affected zones',
      'Testing large cross-section samples',
    ],
    specs: [
      { param: 'Indenter', value: '10 mm tungsten carbide ball' },
      { param: 'Load Range', value: '187.5 kgf to 3000 kgf' },
      { param: 'HB Range', value: '16 HB to 650 HB' },
      { param: 'Dwell Time', value: '10–15 seconds (steel)' },
      { param: 'Measurement Method', value: 'Optical microscope (indentation diameter)' },
      { param: 'Min Specimen Thickness', value: '10× impression depth' },
      { param: 'Standards', value: 'ISO 6506 / ASTM E10 / DIN 50351' },
    ],
    applications: [
      'Foundry and casting quality control',
      'Structural steel mill inspection',
      'Weld qualification testing',
      'Large forging hardness verification',
    ],
  },
  {
    id: '19',
    name: 'Vickers Hardness Tester',
    category: 'hardness',
    categoryLabel: 'Hardness Testing',
    accuracy: '±5 HV',
    standard: 'ISO 6507',
    color: '#2C3E50',
    lightColor: '#D5D8DC',
    image: require('../../assets/images/measuring/vernier.png'),
    description:
      'The Vickers test uses a square-based diamond pyramid indenter over a wide load range, suitable for testing thin sections, coatings, case depths, and very hard materials.',
    useCases: [
      'Testing thin sections, coatings, and plated layers',
      'Measuring case depth hardness gradient',
      'Testing hardened tool steels and cemented carbides',
      'Microhardness testing of individual microstructure phases',
      'Surface treatment quality verification',
    ],
    specs: [
      { param: 'Indenter', value: 'Square pyramid diamond (136° apex angle)' },
      { param: 'Load Range', value: '10 gf to 100 kgf' },
      { param: 'HV Range', value: '5 HV to 3000 HV' },
      { param: 'Measurement Method', value: 'Optical: diagonal length of indentation' },
      { param: 'Accuracy', value: '±5 HV' },
      { param: 'Standards', value: 'ISO 6507 / ASTM E92 / DIN 50133' },
      { param: 'Calibration', value: 'Certified Vickers hardness reference blocks' },
    ],
    applications: [
      'Thin film and coating hardness testing',
      'Nitriding and carburizing case depth measurement',
      'Aerospace and precision instrument materials testing',
      'Research and failure analysis laboratories',
    ],
  },
];